# Generated by Django 6.0.3 on 2026-03-10 07:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shield_id', models.CharField(db_index=True, max_length=11, unique=True)),
                ('encrypted_name', models.TextField()),
                ('encrypted_email', models.TextField()),
                ('encrypted_age', models.TextField()),
                ('age_range', models.CharField(max_length=32)),
                ('verified', models.BooleanField(default=True)),
                ('passkey_challenge', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_id', models.CharField(db_index=True, max_length=13, unique=True)),
                ('course_title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='shieldid.identityprofile')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
